[package]
name = "kcl-api"
version = "0.1.108"
edition = "2024"
description = "KCL interpreter API"
license = "MIT"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.99"

[dependencies]
indexmap.workspace = true
kcl-error = { version = "0.1", path = "../kcl-error" }
serde = { workspace = true }
ts-rs = { version = "11.1.0", features = [
  "uuid-impl",
  "url-impl",
  "chrono-impl",
  "indexmap-impl",
  "no-serde-warnings",
  "serde-json-impl",
] }

[lints]
workspace = true
