[package]
name = "kcl-test-server"
description = "A test server for KCL"
version = "0.1.1"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1.0.86"
hyper = { version = "1.4.0", features = ["server"] }
kcl-lib = { version = "0.1.62", path = "../kcl" }
pico-args = "0.5.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.119"
tokio = { version = "1.38.0", features = ["macros", "rt-multi-thread"] }
