on:
  push:
    branches:
      - main
  workflow_dispatch:
name: Security
permissions:
  # Permissions for Scorecard
  contents: read
  issues: read
  pull-requests: read
  checks: read
jobs:
  security:
    uses: KittyCAD/gha-workflows/.github/workflows/security-default-branch.yml@main
    secrets: inherit
