on:
  push:
    branches:
      - main
      - security
  workflow_dispatch:
permissions:
  contents: read
name: Security
jobs:
  security:
    uses: KittyCAD/gha-workflows/.github/workflows/security.yml@security
    secrets: inherit